"""baza danych aby zmniejszyć rozmiar pliku main.py i ułatwić zarządzanie scenami fabularnymi"""
# pylint: disable=line-too-long
SCENY_FABULARNE = [
    ("Dział wdrożeń", "Trafiasz na stos nieopisanych kabli. Co robisz?", "Oznaczam je", "Zwijam je do szuflady", "Porządkujesz stanowisko i zyskujesz uznanie.", "Szuflada przestaje się domykać, a Janusz to zauważa."),
    ("Klient premium", "Klient prosi o prezentację na już.", "Przygotowuję skrót", "Obiecuję pełną wersję", "Konkretna prezentacja ratuje spotkanie.", "Brak pełnej wersji szybko wychodzi na jaw."),
    ("Kuchnia biurowa", "Ktoś zjada Twój podpisany lunch.", "Pytam spokojnie", "Piszę pasywno-agresywną kartkę", "Sprawca oddaje kanapkę i przeprasza.", "Kartka trafia prosto do Janusza."),
    ("Excel grozy", "W arkuszu znikają wszystkie formuły.", "Sprawdzam historię wersji", "Wpisuję liczby ręcznie", "Historia wersji przywraca raport.", "Jedna cyfra psuje cały budżet."),
    ("Nowy stażysta", "Stażysta pyta Cię o wszystko naraz.", "Robię mu krótkie szkolenie", "Odsyłam go do Janusza", "Stażysta odciąża Cię później przy pracy.", "Janusz odsyła go z powrotem, już zirytowanego."),
    ("Poranny meeting", "Janusz chce pomysł na oszczędności.", "Proponuję automatyzację", "Proponuję mniej kawy", "Pomysł brzmi sensownie i daje Ci premię.", "Całe biuro patrzy na Ciebie z niedowierzaniem."),
    ("Zaginiona faktura", "Księgowość nie może znaleźć ważnej faktury.", "Szukam w archiwum", "Mówię, że to nie moja sprawa", "Odnajdujesz fakturę między starymi raportami.", "Księgowość dopisuje Twoje nazwisko do problemu."),
    ("Dostawa krzeseł", "Kuriera interesuje tylko podpis i ucieczka.", "Sprawdzam liczbę paczek", "Podpisuję w ciemno", "Brakuje tylko jednej śrubki, da się przeżyć.", "Okazuje się, że brakuje połowy krzeseł."),
    ("Prezentacja zarządu", "Slajdy mają być gotowe przed południem.", "Upraszczam przekaz", "Dodaję więcej wykresów", "Zarząd rozumie przekaz i kiwa głowami.", "Wykresy wyglądają poważnie, ale nic nie tłumaczą."),
    ("Wojna o drukarkę", "Dwa działy chcą drukować jednocześnie.", "Ustalam kolejkę", "Odłączam kabel", "Kolejka działa zaskakująco dobrze.", "Wszyscy zaczynają krzyczeć na siebie."),
    ("Dzień audytu", "Audytor pyta o procedurę bezpieczeństwa.", "Pokazuję dokumentację", "Mówię, że Janusz ją zna", "Dokumentacja robi wrażenie na audytorze.", "Audytor zapisuje coś bardzo długo w notesie."),
    ("Poczta firmowa", "Do wszystkich wysłano pustą wiadomość od Janusza.", "Pomagam ją odwołać", "Udostępniam mema", "Usterka zostaje szybko naprawiona.", "Meme krąży po biurze szybciej niż plotka."),
    ("Projekt Alfa", "Termin projektu Alfa przesunięto na jutro.", "Dzielę pracę na zadania", "Zostaję sam po godzinach", "Zespół dowozi najważniejsze rzeczy.", "Nocna praca odbiera Ci resztki energii."),
    ("Telefon z centrali", "Centrala pyta o wyniki całego miesiąca.", "Podaję sprawdzone dane", "Zgaduje optymistycznie", "Dane się zgadzają i dostajesz pochwałę.", "Centrala prosi o korektę po pięciu minutach."),
    ("Wielki arkusz", "Ktoś zablokował wspólny plik hasłem.", "Pytam właściciela", "Próbuję zgadywać hasło", "Hasło zostaje przekazane bez dramatu.", "Trzy błędne próby blokują plik na godzinę."),
    ("Piątkowy kryzys", "Janusz ogłasza pilny raport przed weekendem.", "Negocjuję zakres", "Zgadzam się na wszystko", "Mniejszy raport da się ukończyć rozsądnie.", "Lista zadań rośnie z każdą minutą."),
    ("Konferencja online", "Mikrofon Janusza jest włączony przed spotkaniem.", "Daję mu znak", "Udaje, że nie słyszę", "Ratujesz sytuację w ostatniej chwili.", "Goście słyszą komentarz o ich prezentacji."),
    ("Firmowy integrator", "Janusz prosi o zorganizowanie integracji.", "Rezerwuję kręgle", "Proponuję zebranie online", "Wieczór przechodzi spokojnie, co jest sukcesem.", "Nikt nie chce włączyć kamery na zebraniu."),
    ("Niespodziewany mail", "Klient grozi reklamacją za opóźnienie.", "Odpowiadam z planem naprawy", "Przekazuję maila dalej", "Klient akceptuje konkretny plan.", "Mail wraca do Ciebie z wielkim czerwonym wykrzyknikiem."),
    ("Tajemniczy budżet", "W budżecie pojawia się pozycja 'motywacja zespołu'.", "Pytam księgowość", "Zatwierdzam ją", "Księgowość poprawia pomyłkę.", "Okazuje się, że kupiono trzy ekspresy do kawy."),
    ("Dzień rekrutacji", "Kandydat pyta, jak wygląda atmosfera w firmie.", "Mówię dyplomatycznie", "Mówię całą prawdę", "Kandydat docenia szczerość bez szczegółów.", "Kandydat wychodzi szybciej, niż przyszedł."),
    ("Aktualizacja systemu", "Komputery chcą się aktualizować w środku pracy.", "Ustalam przerwę", "Klikam 'później' wszystkim", "Aktualizacja kończy się bez strat.", "System i tak zaczyna aktualizację podczas raportu."),
    ("Wizyta inwestora", "Inwestor chce zobaczyć biuro bez uprzedzenia.", "Porządkuję stanowiska", "Chowam bałagan w szafie", "Biuro wygląda profesjonalnie przez całe pięć minut.", "Szafa otwiera się dokładnie przy inwestorze."),
    ("Wielka promocja", "Marketing obiecuje klientom funkcję, której nie ma.", "Proszę o poprawkę", "Próbuję ją stworzyć dziś", "Marketing zmienia opis kampanii.", "Funkcja działa, ale tylko na Twoim komputerze."),
    ("Dzień bez Janusza", "Janusz znika na całe przedpołudnie.", "Usprawniam pracę zespołu", "Gram w pasjansa", "Zespół pierwszy raz pracuje bez nerwów.", "Janusz wraca dokładnie, gdy przegrywasz."),
    ("Ostatni raport", "Zbliża się koniec miesiąca i trzeba zamknąć raport.", "Sprawdzam wszystko dwa razy", "Wysyłam od razu", "Raport przechodzi bez jednej poprawki.", "W raporcie brakuje najważniejszej strony."),
    ("Nocny backup", "Serwer przypomina o ostatniej kopii zapasowej.", "Uruchamiam backup", "Odkładam go na jutro", "Kopia kończy się przed końcem zmiany.", "Serwer wybiera najgorszy moment na awarię."),
    ("Finał miesiąca", "Janusz prosi Cię o podsumowanie trzydziestu dni.", "Pokazuję wyniki", "Zrzucam winę na chaos", "Twoje wyniki mówią same za siebie.", "Janusz pamięta każdą wymówkę."),
]
